apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pai-daemon-service-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for PAI daemon service only."
