# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

service_type: "common"

port: 9093
actions-available:
- webportal-notification
- cordon-nodes
alert-handler:
  log-level: 'info'
  port: 9095
  configured: False
cluster-utilization:
  configured: False
job-status-change-notification:
  # Max connection number to database in poller.
  configured: False
  log-level: 'info'
  db-poller-max-db-connection: 10
  db-poller-interval-second: 120
use-pylon: False
repeat-interval: '24h'
cert-expiration-checker:
  schedule: '0 0 * * *'
  alert-residual-days: 30
  cert-path: '/etc/kubernetes/ssl'
