# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

cluster-type:
  - k8s

prerequisite:
  - cluster-configuration
  - docker-cache

template-list:
  - marketplace-webportal.yaml
  - start.sh

start-script: start.sh
stop-script: stop.sh
delete-script: delete.sh
refresh-script: refresh.sh

deploy-rules:
  - in: pai-master
