# Copyright (c) Microsoft Corporation
# All rights reserved.
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
# to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


common:
  cluster-id: pai

  # Cluster type must be yarn or k8s, default value is yarn.
  cluster-type: yarn

  # HDFS, zookeeper data path on your cluster machine.
  data-path: "/datastorage"

  job-history: "true"

  qos-switch: "true"

  az-rdma: "false"

  # If RBAC is enabled in your cluster, you should set this value to true.
  # If RBAC is enabled in your cluster, please ensure the kubeconfig for paictl has enough permission.
  k8s-rbac: "false"

  # If Pai will be deployed in aks, you should set this value to true.
  deploy-in-aks: "false"

  docker-data-root: "/var/lib/docker"


# the docker registry to store docker images that contain system services like frameworklauncher, hadoop, etc.
docker-registry:

  # domain/namespace/

  # If public, please fill it the same as your username
  namespace: openpai

  # E.g., gcr.io. If publicï¼Œfill docker_registry_domain with word "public"
  # domain: public
  domain: docker.io

  # If the docker registry doesn't require authentication, please comment out docker_username and docker_password
  #username: your_registry_username
  #password: your_registry_password

  tag: latest

  # The name of the secret in kubernetes will be created in your cluster
  # Must be lower case, e.g., regsecret.
  secret-name: regsecret
