apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dshuttle-worker
  labels:
    app: dshuttle-worker
spec:
  selector:
    matchLabels:
      app: dshuttle-worker
  template:
    metadata:
      labels:
        app: dshuttle-worker
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: pai-worker
                  operator: In
                  values:
                  - "true"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        fsGroup: 1000
      nodeSelector:
      initContainers:
      - name: socket-chown
        securityContext:
          runAsUser: 0
        image: dshuttle/dshuttle:latest
        command: ["/bin/chown","-R", "1000:1000", "/opt/domain", "/opt/logs", "/mnt/hdd"]
        volumeMounts:
        - name: dshuttle-domain
          mountPath: /opt/domain
        - name: worker-logs
          mountPath: /opt/logs
        - name: hdd
          mountPath: /mnt/hdd
      containers:
        - name: dshuttle-worker
          image: dshuttle/dshuttle:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            limits:
              cpu: 2
              memory: 4G
            requests:
              cpu: 1
              memory: 2G
          command: ["/entrypoint.sh"]
          args:
            - worker-only
            - --no-format
          env:
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          envFrom:
          - configMapRef:
              name: dshuttle-config
          ports:
          - containerPort: 29999
            name: rpc
          - containerPort: 30000
            name: web
          volumeMounts:
            - name: dshuttle-domain
              mountPath: /opt/domain
            - mountPath: /dev/shm
              name: mem
            - mountPath: /mnt/hdd
              name: hdd
            - name: worker-logs
              mountPath: /opt/alluxio/logs
        - name: dshuttle-job-worker
          image: dshuttle/dshuttle:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2
              memory: 2G
            requests:
              cpu: 1
              memory: 1G
          command: ["/entrypoint.sh"]
          args:
            - job-worker
          env:
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          envFrom:
          - configMapRef:
              name: dshuttle-config
          ports:
          - containerPort: 30001
            name: job-rpc
          - containerPort: 30002
            name: job-data
          - containerPort: 30003
            name: job-web
          volumeMounts:
            - name: dshuttle-domain
              mountPath: /opt/domain
            - mountPath: /dev/shm
              name: mem
            - mountPath: /mnt/hdd
              name: hdd
            - name: worker-logs
              mountPath: /opt/alluxio/logs
      restartPolicy: Always
      volumes:
        - name: dshuttle-domain
          hostPath:
            path: /tmp/alluxio-domain
            type: DirectoryOrCreate
        - name: worker-logs
          hostPath:
            path: /var/log/dshuttle
            type: DirectoryOrCreate
        - name: hdd
          hostPath:
            path: /mnt/dshuttle/hdd
            type: DirectoryOrCreate
        - name: mem
          emptyDir:
            medium: "Memory"
            sizeLimit: 2G
