apiVersion: v1
kind: ServiceAccount
metadata:
  name: ca-resource-account
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ca-resource-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ca-resource-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ca-resource-role
subjects:
- kind: ServiceAccount
  name: ca-resource-account
  namespace: default
