# If you set OIDC as the value false, the basic authentication will be applied to your cluster.
OIDC: false

#######################################################################################################################
##########################################     OIDC Configuration    ##################################################
#######################################################################################################################

# If OIDC is set as the value true, you will have to configure the following properties.
#OIDC-type: AAD
#
#AAD:
#  # If you wanna configure AAD-OIDC for OpenPAI, the following configuration is mandatory.
#  # AZURE: https://login.microsoftonline.com/{tenantID}/v2.0/.well-known/openid-configuration
#  # China: https://login.partner.microsoftonline.cn/{tenantID}/v2.0/.well-known/openid-configuration
#  # Germany: https://login.microsoftonline.de/{tenantID}/v2.0/.well-known/openid-configuration
#  wellKnownURL: https://login.microsoftonline.com/{tenantID}/v2.0/.well-known/openid-configuration
#
#  # required
#  tenantID: ${tenat_id}
#
#  # Required, the client ID of your app in AAD
#  clientID: ${your_client_id}
#
#  # Required if `responseType` is 'code', 'id_token code' or 'code id_token'.
#  # If app key contains '\', replace it with '\\'.
#  clientSecret: '${your_client_secret}'
#
#  # Optional. The lifetime of nonce in session or cookie, the default value is 3600 (seconds).
#  nonceLifetime: null
#
#  # Optional. The max amount of nonce saved in session or cookie, the default value is 10.
#  nonceMaxAmount: 5
#
#  # Optional. The clock skew allowed in token validation, the default value is 300 seconds.
#  clockSkew: null


#######################################################################################################################
####################################   Group ManagerConfiguration    ##################################################
#######################################################################################################################

group-manager:
  # basic: If you set group-data-source as the value basic, admin should manually modify user's grouplist.
  # winbind: If you set group-data-source as the value winbind, the user's grouplist will get from winbind server based on your configuration.
  # ms-graph: If you manage your group through azure ad. And you have the permission directory.read.all. You could choose this solution.
  group-data-source: basic

  # If you set winbind as your data source, you should configure this configuraiton.
  # winbind-server-address: xxxxxxx

  # Admin group name and its user list
  admin-group:
    groupname: admingroup
    description: "admin's group"
    # If ms-graph, please fill email alias (email nick name)
    # If winbind server, fill the format from your winbind server.
    externalName: ""
    extension:
      # Group role and acls
      # acls.virtualClusters is a list of group available VCs, by default it's an empty list
      # acls.admin is group permission, admin group have privilege to access all VCs and permission to operate system
      acls:
        virtualClusters: []
        admin: true

  # Group for default vc.
  # For yarn default queue hack.
  default-group:
    groupname: default
    description: "group for default vc"
    externalName: ""
    extension:
      acls:
        virtualClusters: ["default"]
        admin: false

  # If the following groups are not in the data store, it will be created by default.
  grouplist:
    - groupname: forexample
      # internal name
      description: forexample
      # description of the group
      externalName: ""
      # external name, it should be set if your group-data-source is winbind. And the name will be used to query and match the group from
      # the result of winbind. If the group-data-source is basic, this field is useless.