# If you set OIDC as the value false, the basic authentication will be applied to your cluster.
OIDC: false

#######################################################################################################################
##########################################     OIDC Configuration    ##################################################
#######################################################################################################################

# If OIDC is set as the value true, you will have to configure the following properties.
#OIDC-type: AAD
#
#AAD:
#  # If you wanna configure AAD-OIDC for OpenPAI, the following configuration is mandatory.
#
#  # Required
#  identityMetadata: https://login.microsoftonline.com/${tenant_name}.onmicrosoft.com/.well-known/openid-configuration
#  # or equivalently: https://login.microsoftonline.com/<tenant_guid>/.well-known/openid-configuration
#  #
#  # or you can use the common endpoint
#  # 'https://login.microsoftonline.com/common/.well-known/openid-configuration'
#  # To use the common endpoint, you have to either set `validateIssuer` to false, or provide the `issuer` value.
#
#  # Required, the client ID of your app in AAD
#  clientID: ${your_client_id}
#
#  # Required if `responseType` is 'code', 'id_token code' or 'code id_token'.
#  # If app key contains '\', replace it with '\\'.
#  clientSecret: '${your_client_secret}'
#
#  # If you wanna configure AAD-OIDC for OpenPAI, the configuration above is mandatory.
#
#  # Optional configure, default value is 'code id_token'. And its value must be 'code', 'code id_token', 'id_token code' or 'id_token'
#  responseType: 'code id_token'
#
#  # Optional configure, default value is 'form_post'
#  responseMode: 'form_post'
#
#  # Optional configure, default value is true.
#  allowHttpForRedirectUrl: true
#
#  # Optional configure, default value is true. Configuration to set to false if you don't want to validate issuer
#  validateIssuer: true
#
#  # Optional configure default value is false. Configuration to set to true if you are using B2C endpoint
#  # This sample is for v1 endpoint only, so we set it to false
#  isB2C: false
#
#  # Optional configure. If you want to provide the issuer(s) you want to validate instead of using the issuer from metadata
#  issuer: null
#
#  # Optional configure default value is false. Configuration to set to true if the `verify` function has 'req' as the first parameter
#  passReqToCallback: false
#
#  #Recommended to set to true. By default we save state in express session, if this option is set to true, then
#  #we encrypt state and save it in cookie instead. This option together with { session: false } allows your app
#  #to be completely express session free.
#  useCookieInsteadOfSession: true,
#
#  # Optional configure, but suggest to configure it. If `useCookieInsteadOfSession` is set to true. You can provide multiple set of key/iv pairs for key
#  # rollover purpose. We always use the first set of key/iv pair to encrypt cookie, but we will try every set of
#  # key/iv pair to decrypt cookie. Key can be any string of length 32, and iv can be any string of length 12.
#  cookieEncryptionKeys:
#    - key: '12345678901234567890123456789012'
#      iv: '123456789012'
#    - key: 'abcdefghijklmnopqrstuvwxyzabcdef'
#      iv: 'abcdefghijkl'
#
#  # Optional. The additional scope you want besides 'openid', for example: ['email', 'profile'].
#  scope: null
#
#  # Optional, 'error', 'warn' or 'info'
#  loggingLevel: info
#
#  # Optional. The lifetime of nonce in session or cookie, the default value is 3600 (seconds).
#  nonceLifetime: null
#
#  # Optional. The max amount of nonce saved in session or cookie, the default value is 10.
#  nonceMaxAmount: 5
#
#  # Optional. The clock skew allowed in token validation, the default value is 300 seconds.
#  clockSkew: null
#
#  # Optional.
#  # If you want to get access_token for a specific resource, you can provide the resource here; otherwise,
#  # set the value to null.
#  # Note that in order to get access_token, the responseType must be 'code', 'code id_token' or 'id_token code'.
#  resourceURL: 'https://graph.windows.net'


#######################################################################################################################
####################################   Group ManagerConfiguration    ##################################################
#######################################################################################################################

group-manager:
  # basic: If you set group-data-source as the value basic, admin should manually modify user's grouplist.
  # winbind: If you set group-data-source as the value winbind, the user's grouplist will get from winbind server based on your configuration.
  group-data-source: basic

  # If you set winbind as your data source, you should configure this configuraiton.
  # winbind-server-address: xxxxxxx

  # Admin group name and its user list
  admin-group:
    - groupname: admingroup
      description: "admin's group"
      externalName:
      extension:
      userlist:
        - openpai

  # If the following groups are not in the data store, it will be created by default.
  grouplist:
    - groupname: for-example
      # internal name
      description: for-example
      # description of the group
      externalName:
      # external name, it should be set if your group-data-source is winbind. And the name will be used to query and match the group from
      # the result of winbind. If the group-data-source is basic, this field is useless.
      extension:
      # extension field
