# Copyright (c) Microsoft Corporation
# All rights reserved.
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
# to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

clusterID: your_cluster_id


clusterinfo:

  # HDFS, zookeeper data path
  dataPath: "/datastorage"

  # static docker-version
  # https://download.docker.com/linux/static/stable/x86_64/docker-17.06.2-ce.tgz
  # Docker client used by hadoop NM (node manager) to launch Docker containers (e.g., of a deep learning job) in the host env.
  dockerverison: 17.06.2

  # the docker registry to store docker images that contain system services like frameworklauncher, hadoop, etc.
  dockerregistryinfo:

    # If public, please fill it the same as your username
    docker_namespace: your_registry_namespace

    # E.g., gcr.io. If publicï¼Œfill docker_registry_domain with word "public"
    # docker_registry_domain: public
    docker_registry_domain: your_registry_domain
    # If the docker registry doesn't require authentication, please leave docker_username and docker_password empty
    docker_username: your_registry_username
    docker_password: your_registry_password

    # The name of the secret in kubernetes will be created in your cluster
    # Must be lower case, e.g., regsecret.
    secretname: your_secret_name

  # hadoop config information
  hadoopinfo:
    # If custom_hadoop_binary_path is None, script will download a standard version of hadoop binary for you
    # hadoop-version
    # http://archive.apache.org/dist/hadoop/common/hadoop-2.7.2/hadoop-2.7.2.tar.gz
    custom_hadoop_binary_path: None
    hadoopversion: 2.7.2
    configmapname: hadoop-configuration
    hadoop_vip: 10.0.3.9

  frameworklauncher:
    frameworklauncher_vip: 10.0.3.9
    frameworklauncher_port: 9086

  restserverinfo:
    # path for rest api server src dir
    src_path: ../rest-server/
    # uri for frameworklauncher webservice
    webservice_uri: http://10.0.3.9:9086
    # uri for hdfs
    hdfs_uri: hdfs://10.0.3.9:9000
    # port for rest api server
    server_port: 9186
    # secret for signing authentication tokens, for example, "Hello PAI!"
    jwt_secret: your_jwt_secret
    # default database file name
    lowdb_file: your_database_file_name
    # default admin username
    lowdb_admin: your_admin_username
    # default admin password
    lowdb_passwd: your_admin_password

  # The config for web portal
  webportalinfo:
    # uri for rest server
    rest_server_uri: http://10.0.3.9:9186
    # uri of k8s dashboard
    k8s_dashboard_uri: http://10.0.3.9:9090
    # uri of grafana portal
    grafana_uri: http://10.0.3.9:9090
    # port for webportal
    server_port: 9286


# The detail machine type information in your cluster, each machine type has an entry here
# An Azure VM example
machineinfo:

  NC24R:
    mem: 224
    gpu:
    # type: gpu{type}
      type: teslak80
      count: 4
    cpu:
      vcore: 24
    dataFolder: "/mnt"
    # Note: Up to now, the only supported os version is Ubuntu16.04. Please do not change it here.
    os: ubuntu16.04

  D8SV3:
    mem: 32
    cpu:
      vcore: 8
    dataFolder: "/mnt"
    # Note: Up to now, the only supported os version is Ubuntu16.04. Pls don't change it here.
    os: ubuntu16.04


# The machine list in your cluster
# An example
machinelist:
  # Replace your own hostname here.
  infra-03:
    # recommend to be the same as host IP
    nodename: 10.0.3.9
    # Replace your own machine type here
    machinetype: D8SV3
    # Replace your own IP here.
    ip: 10.0.3.9
    # all hadooprole: master will install zk, please specify a unique zkid for each node. Begin at "1".
    zkid: "1"
    # hdfsrole:   master or worker
    # yarnrole:   master or worker
    # zookeeper:  "true"   or not set this value
    # Note: if zookeeper is set, you should set zkid in this machine.
    # jobhistory: "true"   or not set this value
    hdfsrole: master
    yarnrole: master
    zookeeper: "true"
    jobhistory: "true"
    launcher: "true"
    restserver: "true"
    webportal: "true"
  
  # Do the same work as the machine above.
  worker-01:
    nodename: 10.0.3.11
    machinetype: NC24R
    ip: 10.0.3.11
    hdfsrole: worker
    yarnrole: worker
  
  # Do the same work as the machine above.
  worker-02:
    nodename: 10.0.3.12
    machinetype: NC24R
    ip: 10.0.3.12
    hdfsrole: worker
    yarnrole: worker