kubeApiServerAddress: http://10.151.41.16:8080

physicalCluster:
  gpuTypes:
    K80:
      gpu: 1
      cpu: 4
      memory: 8192Mi
    M60:
      gpu: 1
      cpu: 4
      memory: 8192Mi
  cellTypes:
    K80-2GPU:
      childCellType: K80
      childCellNumber: 2
    K80-NODE:
      childCellType: K80-2GPU
      childCellNumber: 2
      isNodeLevel: true
    K80-NODE-POOL:
      childCellType: K80-NODE
      childCellNumber: 4
    M60-2GPU:
      childCellType: M60
      childCellNumber: 2
    M60-NODE:
      childCellType: M60-2GPU
      childCellNumber: 2
      isNodeLevel: true
    M60-NODE-POOL:
      childCellType: M60-NODE
      childCellNumber: 1

  physicalCells:
  - cellType: K80-NODE-POOL
    cellChildren:
    - cellAddress: 10.151.41.18
    - cellAddress: 10.151.41.19
    - cellAddress: 10.151.41.23
    - cellAddress: 10.151.41.24
    # - cellAddress: 10.151.41.25

virtualClusters:
  VC1:
    virtualCells:
    - cellType: K80-NODE-POOL.K80-NODE
      cellNumber: 1
  default:
    virtualCells:
    - cellType: K80-NODE-POOL.K80-NODE
      cellNumber: 2