protocolVersion: 2
name: itc-reconfig-2
type: job
prerequisites:
  - protocolVersion: 2
    name: keras_tensorflow_example
    type: dockerimage
    uri: openpai/pai.example.keras.tensorflow
taskRoles:
  train:
    instances: 2
    completion:
      minFailedInstances: 1
      minSucceededInstances: 2
    dockerImage: keras_tensorflow_example
    resourcePerInstance:
      cpu: 16
      memoryMB: 32768
      gpu: 4
    commands:
      - rm /usr/local/cuda/lib64/stubs/libcuda.so.1
      - python mnist_cnn.py
defaults:
  virtualCluster: VC1
extras:
  hivedScheduler:
    jobPriorityClass: test
    taskRoles:
      train:
        gpuType: M60
  submitFrom: submit-job-v2
