# This is the error patten used to distinguage user error and system error
# We collect such info from user log/runtime log and user exit code, and user
# This spec to generate aggregated error

# [200, 219] reserved by FC

- patterns:
  - exitCode: 1
    userLogRegex: exec\(compile\(getattr\(token[a-z]*, 'open', open\)\(__file__\)
  reason: Failed to open tocken file
  solution:
    - Please check the tocken file path
  containerExitCode: 10

- patterns:
  - exitCode: 1
    userLogRegex: failed with error code 1 in /tmp/[a-z]*
  - exitCode: 1
    userLogRegex: package not find [a-z]*
  reason: Some package not install property
  solution:
    - Please check the pip install command
  containerExitCode: 12

- patterns:
  - exitCode: 1
    userLogRegex: connect tensorboard failed
    platformLogRegex: Failed to start tensorboard
  reason: Tensorboad not startup correctly
  solution:
    - Please try again or connect admin
  containerExitCode: 15

- patterns:
  - exitCode: 137
  reason: User program terminated by SIGKILL
  solution:
    - Please check the log and retry again
  containerExitCode: 137

- patterns:
  - exitCode: 143
  reason: User program terminated by SIGTERM
  solution:
    - Please check the log and retry again
  containerExitCode: 143